#api:
#    resource: "@APIBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mvms_api:
    type:     rest
    prefix:   /api
    resource: "@APIBundle/Resources/config/api-routing.yml"
